main:
    project: 'servo_sim'
    disable_wandb: False
paths:
    home: /home/buechner/
    package: /home/buechner/servoing/flowcontrol/
    dataroot: /home/buechner/servoing/data/
    rel_dataset: single_contrastive_bidir/
    checkpoints: /home/buechner/servoing/checkpoints/
    split: train
    config_name: demo_shape_sorting_trapeze_rP/
preprocessing:
    raw_data: demonstrations_raw_large/
    rel_export_dir: single_contrastive_bidir/ # single_contrastive_bidir
    workers: 10
    num_episodes: 500
    task: shape_sorting # shape_sorting, pick_n_place
    object_selected: semicircle # trapeze, oval, semicircle
    task_variant: rP # rotation plus (+-pi)
model:
    split_idx: 450
    device: cuda
    num_img_chs: 3 # e.g. [RGB, depth, mask] = 5
    batch_size: 32
    dataparallel: False
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 100
    depth: 6
    loader_workers: 8
    weight_decay: 1e-4
eval:
    checkpoint: servo_simnet_bright-kumquat-202_008.pth
    device: cuda
    