main:
    project: 'servo_graph'
    disable_wandb: False
paths:
    home: /home/buechner/
    package: /home/buechner/servoing/flowcontrol/
    dataroot: /home/buechner/servoing/data/
    checkpoints: /home/buechner/servoing/checkpoints/
    rel_dataset: flow_dataset_contrastive/
    split: train
    config_name: demo_shape_sorting_trapeze_rP/
preprocessing:
    num_cpus: 4
model:
    device: cuda
    batch_size: 2
    dataparallel: False
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 100
    depth: 6
    loader_workers: 1
    weight_decay: 1e-4