main:
    project: 'servo_sim'
    disable_wandb: False
paths:
    home: /home/buechner/
    package: /home/buechner/servoing/flowcontrol/
    dataroot: /home/buechner/servoing/data/
    rel_dataset: single_contrastive/
    checkpoints: /home/buechner/servoing/checkpoints/
    split: train
    config_name: demo_shape_sorting_trapeze_rP/
preprocessing:
    raw_data: demonstrations_raw_large/
    rel_export_dir: single_contrastive/
    workers: 3
    num_episodes: 500
    task: shape_sorting # shape_sorting, pick_n_place
    object_selected: trapeze # trapeze, oval, semicircle
    task_variant: rP # rotation plus (+-pi)
model:
    split_idx: 50
    device: cuda
    batch_size: 1
    dataparallel: False
    lr: 1e-3
    beta_lo: 0.9
    beta_hi: 0.999
    num_epochs: 100
    depth: 6
    loader_workers: 4
    weight_decay: 1e-4