"""
This module updates the the sys.path.

The sys.path variable is a global variable, so importing this  module, will
change the path for the importing file.

This implies the directory structure:
    /somepath/gym-grasping
    /somepath/IRR
    /somepath/flownet2
"""
import os
import sys
import json
from types import SimpleNamespace

dirname = os.path.dirname(os.path.abspath(__file__))
module_dir = os.path.abspath(os.path.join(dirname, "../../"))
if module_dir not in sys.path:
    sys.path.append(module_dir)


# Module argument management
def check_args_serializable(args):
    try:
        return bool(json.dumps(vars(args)))
    except TypeError:
        print(vars(args))
        return False


def save_args(args, filename):
    if os.path.isfile(filename):
        print("Args file already exits", filename)
        raise ValueError

    with open(filename, "w") as outfile:
        json.dump(vars(args), outfile)


def load_args(filename):
    """
    Loads module arguments from file. Files can be generated by
    overload_default_args(save=True)

    Args:
        filename of arg file.

    Returns:
        Args object used by module

    """
    with open(filename) as infile:
        arg_vars = json.load(infile)
    args = SimpleNamespace(**arg_vars)
    return args
